version: '3.1'

# Responsible for bringing up the following services:
# - Kafka
# - Schema Registry
# - Kafka REST Proxy
# - Kafka Connect
# - ZooKeeper
# - Landoop UI
#
# https://hub.docker.com/r/landoop/fast-data-dev/
# Make sure to docker pull landoop/fast-data-dev:latest before running docker-compose
# Allocate at-least 4GB of memory to run this container

# Start-up
# docker-compose -f fast-data-docker-compose.yaml up

# Clean-up
# docker-compose -f fast-data-docker-compose.yaml down --volume
services:
  fast-data:
    image: landoop/fast-data-dev:latest
    ports:
      - "9092:9092"   # Kafka broker
      - "8081:8081"   # Schema Registry
      - "8082:8082"   # Kafka REST Proxy
      - "8083:8083"   # Kafka Connect
      - "2182:2181"   # Zookeeper
      - "3030:3030"   # Landoop Development Environment UI
    environment:
      - "ADV_HOST=127.0.0.1"  # Allow services in container to be remotely accessible (so the host can access it)
      - "SAMPLEDATA=0"        # Do not create example topics
      - "FORWARDLOGS=0"       # Disable the 5 file source connectors that automatically bring logs into Kafka topics
      - "RUNTESTS=0"          # Don't run Coyote integration tests on container startup (enable if debugging)
    networks:
      - fast-data

networks:
  fast-data:
